name: frontend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <4.0.0'

dependencies:
  provider: ^6.0.5
  http: ^1.6.0
  shared_preferences: ^2.0.15
  win32: ^5.5.0
#  dynamic_color: ^1.6.0
  lucide_icons: ^0.257.0
#  flutter_secure_storage: ^8.0.0
#  flutter_rating_bar: ^4.0.0
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.3
  
  # AR & 3D Model Viewer
  model_viewer_plus: ^1.8.1
  webview_flutter: ^4.10.0
  readmore: ^3.0.0
  share_plus: ^10.1.4

  # لفتح الروابط الخارجية (الخرائط)
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.14.0

  # Text-to-Speech للقراءة الصوتية
  flutter_tts: ^4.0.2

  # Image Picker لاختيار صور البروفايل
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

# إعدادات أيقونة التطبيق
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/images/logo1.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/fonts/   # <--- تمت إضافته فونت الخط المسند
    - assets/models/  # <--- نماذج 3D للواقع المعزز

  fonts:
    - family: OldSouthArabian
      fonts:
        - asset: assets/fonts/NotoSansOldSouthArabian-Regular.ttf
