name: frontend
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  http: ^1.6.0
  shared_preferences: ^2.0.15
  win32: ^5.5.0
  lucide_icons: ^0.257.0

  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^17.1.2

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.3.3

  model_viewer_plus: ^1.8.1
  webview_flutter: ^4.10.0
  readmore: ^3.0.0
  share_plus: ^10.1.4
  url_launcher: ^6.2.5
  google_maps_flutter: ^2.14.0
  flutter_tts: ^4.0.2
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo1.png"
  min_sdk_android: 21
  adaptive_icon_background: "#1a1a2e"
  adaptive_icon_foreground: "assets/images/logo1.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/models/

  fonts:
    - family: OldSouthArabian
      fonts:
        - asset: assets/fonts/NotoSansOldSouthArabian-Regular.ttf
